################################################################################
#                                                                              #
# Local config settings to customize this HPCTest installation.                #
# They override the builtin settings in runner/src/config-builtin.yaml.        #
# Edit as desired.                                                             #
#                                                                              #
################################################################################


profile:
  hpctoolkit bin path: ~/hpctoolkit-current/hpctoolkit/INSTALL/bin/
  
run:
  ulimit:
    t: unlimited  # cpu time (seconds)

  
  
  
  
  
