################################################################################
#                                                                              #
# Local config settings to customize this HPCTest installation.                #
#                                                                              #
# They override the builtin settings in                                        #
#       internal/src/config-data/config-default.yaml                           #
#                                                                              #
# Edit as needed.                                                              #
#                                                                              #
################################################################################


profile:
  hpctoolkit:
    # if path is commented out, the user's PATH setting will be used for the
    #    bits to be tested.
    # path: ~/hpctoolkit/INSTALL/
    #
    #  define the parameters used for the experiments run in the tests
    hpcrun params:     "REALTIME@10000"
    hpcstruct params:  ""  
    hpcprof params:    ""  



config:
#    batch:
#      manager: Slurm
#      default: false
#      params:
#        account:   commons
#        partition: commons
#        time:      "1:00:00"
run:
  ulimit:
    t: unlimited  # cpu time (seconds)


 
