################################################################################
#                                                                              #
# Local config settings to customize this HPCTest installation.                #
# They override the builtin settings in internal/src/config-builtin.yaml.      #
# Edit as needed.                                                              #
#                                                                              #
################################################################################


profile:
  hpctoolkit:
    path: ~/hpctoolkit/INSTALL/
config:
#    batch:
#      manager: Slurm
#      default: false
#      params:
#        account:   commons
#        partition: commons
#        time:      "1:00:00"
run:
  ulimit:
    t: unlimited  # cpu time (seconds)


 