################################################################################
#                                                                              #
# Local config settings to customize this HPCTest installation.                #
# They override the builtin settings in runner/src/config-builtin.yaml.        #
# Edit as desired.                                                             #
#                                                                              #
################################################################################


run:
  ulimit:
    t: 100    # cpu time

profile:
  hpctoolkit bin path: ~/hpctoolkit-current/hpctoolkit/INSTALL/bin/
  
  
  
  
  
  
