################################################################################
#                                                                              #
# Local config settings to customize this HPCTest installation.                #
# They override the builtin settings in runner/src/config-builtin.yaml.        #
# Edit as desired.                                                             #
#                                                                              #
################################################################################


profile:
  hpctoolkit:
    path: ~/hpctoolkit-current/hpctoolkit/INSTALL/
config:
# batch:
#   manager: Slurm
#   force:   True
#   default: False
#   params:
#     account:   commons
#     partition: commons
#     time:      "1:00:00"
run:
  ulimit:
    t: unlimited  # cpu time (seconds)

  
  
  
  
 